Memthol.1.0.0
OCamlPro/memthol pull request #11
Opened 2022-10-31 17:01 UTC by hernoufM

This PR :
- Discards warnings.
- Updates parser to support to the recent .ctf format generated by Memtrace.
- Updates inter-documentation links to the new Rust link's format.
- Crate dependencies was updated to the most recent version (except of some of them).
- Build script for `memthol`, that compiles `client` crate to wasm before compilation of himself. That was done to enable installation with ```cargo install```

2022-11-07 15:44 UTC, krtab approved these changes

2022-11-07 15:45 UTC, krtab commented
Woops, I missclicked, only wanted to validate one commit.

2022-11-07 17:25 UTC, hernoufM commented
No problems :smile:

2022-11-08 09:05 UTC, AdrienChampion commented
- [ ] clean doc-links

Generic remark on doc-links: whenever `Item` is in scope where you're writing doc, you can just write `` [`Item`] `` to generate a link. This was not the case when I wrote this code, but now you can remove a lot of citation-style links like

```rust
/// [`SomeType`]: SomeType
```

2022-11-08 09:08 UTC, AdrienChampion commented
It seems you removed `libs/client` from the workspace. The problem with doing this is that you cannot clean the project anymore without manually removing `libs/client/target`. I understand it's because we need to build the wasm part which takes a lock already taken by the server build (hence the use of `cargo-make` previously), but are you positive that's how other projects handle this issue?

2022-11-08 09:22 UTC, AdrienChampion requested changes
- [x] clean doc-links
- [ ] rewrite all `1.0.0` bumps to `0.` as we're not ready for semantic versioning

2022-11-08 09:22 UTC, AdrienChampion commented on libs/charts/src/filter/sub.rs
> +// [`Filter`]: Filter (The Filter struct).
Typo

2022-11-08 09:22 UTC, AdrienChampion commented on libs/client/src/js.rs
> +    // Issues an alert.
Typo?

2022-11-08 09:38 UTC, hernoufM commented
> Generic remark on doc-links: whenever `Item` is in scope where you're writing doc, you can just write `` [`Item`] `` to generate a link. This was not the case when I wrote this code, but now you can remove a lot of citation-style links like
> 
> ```rust
> /// [`SomeType`]: SomeType
> ```

I hesitated to  remove the `[`SomeType`]: SomeType (Some explanation) ` notations because every of them was accompanied with the tip `Some explanation`, that appears when hoovers over link. But i guess, there are other ways to let those tips using new docs format.

2022-11-08 09:44 UTC, hernoufM commented
> EDIT: couldn't the `build.rs` trigger on `cargo clean` and actually clean?

Actually, build.rs, is executed before compilation of memthol's binary crate, and that in turn needs compiled version of `client` at compile time. So, solution is, in my opinion, to let *build.rs* to move his generated artifacts into the root *target* directory, so it could be removed by `cargo clean`.

2022-11-08 09:45 UTC, hernoufM commented on libs/alloc_data/Cargo.toml
> +version = "1.0.0"
Yes, totally agree!

2022-11-08 09:45 UTC, hernoufM commented on libs/alloc_data/src/lib.rs
> +    ) -> Self {
Oups... I ll do that.

2022-11-08 11:01 UTC, AdrienChampion commented
> > EDIT: couldn't the `build.rs` trigger on `cargo clean` and actually clean?
> 
> Actually, build.rs, is executed before compilation of memthol's binary crate, and that in turn needs compiled version of `client` at compile time. So, solution is, in my opinion, to let _build.rs_ to move his generated artifacts into the root _target_ directory, so it could be removed by `cargo clean`.

Sounds great 🐱

2022-11-08 11:03 UTC, AdrienChampion commented
> > Generic remark on doc-links: whenever `Item` is in scope where you're writing doc, you can just write `` [`Item`] `` to generate a link. This was not the case when I wrote this code, but now you can remove a lot of citation-style links like
> > ```rust
> > /// [`SomeType`]: SomeType
> > ```
> 
> I hesitated to remove the `[`SomeType`]: SomeType (Some explanation) ` notations because every of them was accompanied with the tip `Some explanation`, that appears when hoovers over link. But i guess, there are other ways to let those tips using new docs format.

Yeah let's just use the normal workflow and let `rustdoc` handle tooltips and such. It's more concise and makes docs homogeneous compared to other crates.

2022-11-17 13:52 UTC, AdrienChampion approved these changes
LGTM

2022-11-17 13:53 UTC, merged